import { type NextPage } from "next";
import Head from "next/head";

import { useState } from "react";
import type { FormType } from "../components/LoanForm";
import { LoanForm } from "../components/LoanForm";
import { LoanTable } from "../components/LoanTable";

const Home: NextPage = () => {
  const [formData, setFormData] = useState<FormType>();

  const onFormDataChange = (data: FormType) => {
    setFormData(data);
  };

  return (
    <>
      <Head>
        <title>Student Loan Tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#02096d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Student <span className="text-[hsl(216,92%,76%)]">Loan</span>{" "}
            Tracker
          </h1>
          <div className="flex gap-4 sm:grid-cols-2 md:gap-8">
            <LoanForm onFormDataChange={onFormDataChange} />
            {formData && (
              <LoanTable
                loanBalance={formData?.loanBalance}
                graduatingYear={formData?.graduatingYear}
              />
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
